// Mocks generated by Mockito 5.4.4 from annotations
// in inherited_rxdart/test/src/base_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:inherited_rxdart/inherited_rxdart.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rxdart/rxdart.dart' as _i3;

import 'base_view_model_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReleasableSubjects].
///
/// See the documentation for Mockito's code generation for more information.
class MockReleasableSubjects extends _i1.Mock
    implements _i2.ReleasableSubjects {
  @override
  List<_i3.Subject<dynamic>> get subjects => (super.noSuchMethod(
        Invocation.getter(#subjects),
        returnValue: <_i3.Subject<dynamic>>[],
        returnValueForMissingStub: <_i3.Subject<dynamic>>[],
      ) as List<_i3.Subject<dynamic>>);
}

/// A class which mocks [Handler].
///
/// See the documentation for Mockito's code generation for more information.
class MockHandler<T> extends _i1.Mock implements _i4.Handler<T> {
  @override
  void handle(T? value) => super.noSuchMethod(
        Invocation.method(
          #handle,
          [value],
        ),
        returnValueForMissingStub: null,
      );
}
